export const coursedata = [
  {
    id: 'course001',
    title: 'Data Analytics Bootcamp',
    description: 'Master data analytics with practical, real-world projects.',
    syllabus: 'https://example.com/syllabus/data-analytics',
    lessons: [
      { id: 'lesson001', title: 'Introduction to Data Analytics' },
      { id: 'lesson002', title: 'Data Visualization Basics' },
    ],
    courseImageUrl: '/images/data-analytics-1.jpg',
    instructorId: '63f4f1a79a1b78a123456001',
    price: 499,
  },
  {
    id: 'course002',
    title: 'Full Stack Web Development',
    description: 'Learn to build scalable web applications from scratch.',
    syllabus: 'https://example.com/syllabus/fullstack',
    lessons: [
      { id: 'lesson003', title: 'HTML & CSS Fundamentals' },
      { id: 'lesson004', title: 'Backend with Node.js' },
    ],
    courseImageUrl: '/images/fullstack.jpg',
    instructorId: '63f4f1a79a1b78a123456002',
    price: 599,
  },
  {
    id: 'course003',
    title: 'Introduction to Python Programming',
    description: 'Begin your programming journey with Python basics.',
    syllabus: 'https://example.com/syllabus/python-intro',
    lessons: [
      { id: 'lesson005', title: 'Python Basics' },
      { id: 'lesson006', title: 'Control Structures in Python' },
    ],
    courseImageUrl: '/images/python-intro.jpg',
    instructorId: '63f4f1a79a1b78a123456003',
    price: 199,
  },
  {
    id: 'course004',
    title: 'Machine Learning Advanced',
    description: 'Dive deep into machine learning concepts and algorithms.',
    syllabus: 'https://example.com/syllabus/ml-advanced',
    lessons: [
      { id: 'lesson007', title: 'Supervised Learning' },
      { id: 'lesson008', title: 'Unsupervised Learning' },
    ],
    courseImageUrl: '/images/ml-advanced.jpg',
    instructorId: '63f4f1a79a1b78a123456004',
    price: 699,
  },
  {
    id: 'course005',
    title: 'UI/UX Design Essentials',
    description: 'Create user-centered designs with cutting-edge tools.',
    syllabus: 'https://example.com/syllabus/ui-ux',
    lessons: [
      { id: 'lesson009', title: 'Introduction to UI/UX' },
      { id: 'lesson010', title: 'Wireframing and Prototyping' },
    ],
    courseImageUrl: '/images/ui-ux.jpg',
    instructorId: '63f4f1a79a1b78a123456005',
    price: 399,
  },
  {
    id: 'course006',
    title: 'Cybersecurity Basics',
    description: 'Understand the fundamentals of cybersecurity and best practices.',
    syllabus: 'https://example.com/syllabus/cybersecurity-basics',
    lessons: [
      { id: 'lesson011', title: 'Cybersecurity Fundamentals' },
      { id: 'lesson012', title: 'Common Threats and Countermeasures' },
    ],
    courseImageUrl: '/images/cybersecurity.jpg',
    instructorId: '63f4f1a79a1b78a123456006',
    price: 299,
  },
  {
    id: 'course007',
    title: 'Big Data and Hadoop',
    description: 'Master big data tools and techniques with Hadoop.',
    syllabus: 'https://example.com/syllabus/big-data',
    lessons: [
      { id: 'lesson013', title: 'Introduction to Big Data' },
      { id: 'lesson014', title: 'Hadoop Ecosystem' },
    ],
    courseImageUrl: '/images/big-data.jpg',
    instructorId: '63f4f1a79a1b78a123456007',
    price: 599,
  },
  {
    id: 'course008',
    title: 'Digital Marketing Masterclass',
    description: 'Build skills in SEO, social media, and online marketing.',
    syllabus: 'https://example.com/syllabus/digital-marketing',
    lessons: [
      { id: 'lesson015', title: 'SEO Basics' },
      { id: 'lesson016', title: 'Social Media Strategies' },
    ],
    courseImageUrl: '/images/digital-marketing.jpg',
    instructorId: '63f4f1a79a1b78a123456009',
    price: 349,
  },
  {
    id: 'course009',
    title: 'AI for Everyone',
    description: 'Understand the basics of artificial intelligence.',
    syllabus: 'https://example.com/syllabus/ai-basics',
    lessons: [
      { id: 'lesson017', title: 'AI Fundamentals' },
      { id: 'lesson018', title: 'Applications of AI' },
    ],
    courseImageUrl: '/images/ai-basics.jpg',
    instructorId: '63f4f1a79a1b78a123456011',
    price: 299,
  },
  {
    id: 'course010',
    title: 'Introduction to SQL',
    description: 'Learn to query and manage databases with SQL.',
    syllabus: 'https://example.com/syllabus/sql',
    lessons: [
      { id: 'lesson019', title: 'SQL Basics' },
      { id: 'lesson020', title: 'Advanced SQL Queries' },
    ],
    courseImageUrl: '/images/sql.jpg',
    instructorId: '63f4f1a79a1b78a123456013',
    price: 199,
  },
];
